# Generated by Django 5.0.1 on 2024-01-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmnicellModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Generation', models.CharField(blank=True, max_length=5, null=True)),
                ('Model', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['Generation', 'Model'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
    ]
