# Generated by Django 5.0.1 on 2024-02-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_building_omnicellmodel_site_omnicell_aux_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerator',
            name='Broken',
            field=models.BooleanField(default=False),
        ),
    ]
