# Generated by Django 5.0.1 on 2024-01-23 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_omnicellmodel_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='omnicell',
            name='Area',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='omnicell',
            name='CT_Version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='omnicell',
            name='Emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omnicell',
            name='Ivanti',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omnicell',
            name='Model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.omnicellmodel'),
        ),
        migrations.AddField(
            model_name='omnicell',
            name='PC_Name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='omnicell',
            name='Room',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='omnicell',
            name='Serial_Number',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
