# Generated by Django 5.0.1 on 2024-01-23 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_building_omnicell_area_omnicell_ct_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='omnicell',
            options={'ordering': ['Site', 'Building', 'Area', 'Omni_Id']},
        ),
        migrations.AlterModelOptions(
            name='refrigerator',
            options={'ordering': ['Omnicell', 'Type', 'Facilities_Id']},
        ),
        migrations.AddField(
            model_name='omnicell',
            name='Building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.building'),
        ),
        migrations.AddField(
            model_name='omnicell',
            name='Site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.site'),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='Omnicell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.omnicell'),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='Type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
