# Generated by Django 5.0.1 on 2024-01-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_alter_building_options_alter_omnicell_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omnicell',
            name='PC_Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
