# Generated by Django 5.0.1 on 2024-01-30 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_alter_omnicell_pc_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='omnicell',
            options={'ordering': ['Omni_Id', 'Site', 'Building', 'Area']},
        ),
        migrations.CreateModel(
            name='Aux',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Serial_Number', models.CharField(blank=True, max_length=7, null=True)),
                ('Model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.omnicellmodel')),
                ('Omnicell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.omnicell')),
            ],
            options={
                'ordering': ['Omnicell', 'Model', 'Serial_Number'],
            },
        ),
    ]
