# Generated by Django 5.0.1 on 2024-11-20 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_refrigeratormodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refrigeratormodel',
            options={'ordering': ['ModelName']},
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='Model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.refrigeratormodel'),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='Wheels',
            field=models.BooleanField(default=False),
        ),
    ]
