# Generated by Django 5.0.1 on 2024-02-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_alter_omnicell_options_aux'),
    ]

    operations = [
        migrations.AddField(
            model_name='omnicell',
            name='Door_Code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='omnicell',
            name='Note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
