# Generated by Django 5.0.1 on 2024-11-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_alter_refrigeratormodel_options_refrigerator_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='portLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='omnicell',
            name='Port_Name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
