# Generated by Django 5.0.1 on 2024-02-01 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_omnicell_door_code_omnicell_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lockbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Key', models.CharField(blank=True, max_length=10, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Refrigerator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.refrigerator')),
            ],
            options={
                'ordering': ['Refrigerator'],
            },
        ),
    ]
