# Generated by Django 5.0.1 on 2024-11-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_omnicell_port_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='omnicell',
            name='Boom',
            field=models.BooleanField(default=False),
        ),
    ]
