# Generated by Django 5.0.1 on 2024-02-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_lockbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockbox',
            name='Medication',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
