# Generated by Django 5.0.1 on 2025-10-17 00:42

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_omnicell_boom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Header_BG', colorfield.fields.ColorField(default='#1d3557', image_field=None, max_length=25, samples=None)),
                ('Header_Txt', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('Menu_BG', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('Menu_Txt', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('Search_BG', colorfield.fields.ColorField(default='#598baf', image_field=None, max_length=25, samples=None)),
                ('Search_Txt', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('Content_BG', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('Content_Txt', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('Footer_BG', colorfield.fields.ColorField(default='#4d516d', image_field=None, max_length=25, samples=None)),
                ('Footer_Txt', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
            ],
        ),
    ]
