# Generated by Django 5.0.1 on 2025-10-17 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0010_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auto.theme'),
        ),
    ]
