# Generated by Django 5.0.1 on 2025-10-21 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0011_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Summary', models.CharField(blank=True, max_length=100, null=True)),
                ('Note', models.TextField(blank=True, max_length=500, null=True)),
                ('Solved', models.BooleanField(default=False)),
                ('Opened', models.DateTimeField(blank=True, null=True)),
                ('Closed', models.DateTimeField(blank=True, null=True)),
                ('Ivanti_T', models.CharField(blank=True, max_length=20, null=True)),
                ('Omni_T', models.CharField(blank=True, max_length=20, null=True)),
                ('Closed_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closer', to=settings.AUTH_USER_MODEL)),
                ('Omnicell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.omnicell')),
                ('Opened_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opener', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
