# Generated by Django 5.0.1 on 2025-10-22 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0012_organization_serviceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HdType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='omnicell',
            name='Org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.organization'),
        ),
        migrations.AddField(
            model_name='omnicell',
            name='HD_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.hdtype'),
        ),
    ]
