# Generated by Django 5.0.1 on 2025-10-22 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0013_hdtype_omnicell_org_omnicell_hd_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aux',
            name='Org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.organization'),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='Org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='Org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.organization'),
        ),
    ]
